CREATE DATABASE tools_springframework;
USE tools_springframework;

CREATE TABLE TB_AUTH (
	USER_ID varchar(20) PRIMARY KEY COMMENT '학번/교번', 
	PASSWORD varchar(255) NOT NULL COMMENT '비밀번호'
);

ALTER TABLE TB_AUTH COMMENT ='인증 정보';

CREATE TABLE TB_USER (
	USER_ID varchar(20) PRIMARY KEY COMMENT '학번/교번', 
	USER_NAME varchar(4) NOT NULL COMMENT '이름', 
	USER_EMAIL varchar(50) NOT NULL COMMENT '이메일', 
	USER_PHONE varchar(13) NOT NULL COMMENT '전화번호', 
	USER_REGISTRAION_NUMBER varchar(14) NOT NULL COMMENT '주민번호', 
	USER_PICTURE_URL varchar(200)  COMMENT '증명사진 저장 위치', 
	USER_POST varchar(6)  COMMENT '우편번호', 
	USER_ADDRESS1 varchar(200)  COMMENT '주소', 
	USER_ADDRESS2 varchar(200)  COMMENT '상세주소', 
	MENTOR_PROFESSOR_USER_ID varchar(20)  COMMENT '담당 교수 ID', 
	USER_AVGERAGE_GRADE varchar(4)  COMMENT '평균 학점', 
	USER_INTEREST_FIELD varchar(20)  COMMENT '관심 분야', 
	LAB_ADDRESS1 varchar(200)  COMMENT '연구실 주소', 
	LAB_ADDRESS2 varchar(200)  COMMENT '연구실 주소 상세', 
	LAB_PHONE varchar(13)  COMMENT '연구실 전화번호', 
	USER_TYPE_CODE varchar(2) NOT NULL COMMENT '사용자유형', 
	USER_SCHOOL_CODE varchar(2) NOT NULL COMMENT '학교코드', 
	DEPARTMENT_CODE varchar(2) NOT NULL COMMENT '학과코드', 
	REGISTER_STATUS_CODE varchar(2) NOT NULL COMMENT '학적코드', 
	CREATE_USER_ID varchar(20) NOT NULL COMMENT '등록한사람아이디', 
	UPDATE_USER_ID varchar(20) NOT NULL COMMENT '수정한사람아이디', 
	DELETE_USER_ID varchar(20)  COMMENT '삭제한사람아이디', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14) NOT NULL COMMENT '수정일시', 
	DELETE_DATE_TIME varchar(14)  COMMENT '삭제일시'
);

ALTER TABLE TB_USER COMMENT ='사용자 정보';

CREATE TABLE TB_COUNSEL (
	COUNSEL_NO int PRIMARY KEY COMMENT '상담 신청 번호', 
	PROFESSOR_USER_ID varchar(20) NOT NULL COMMENT '교수', 
	STUDENT_USER_ID varchar(20) NOT NULL COMMENT '학생', 
	REQUEST_TIME varchar(14) NOT NULL COMMENT '상담 일시', 
	PLACE varchar(200)  COMMENT '장소', 
	REQUEST_CONTENT TEXT NOT NULL COMMENT '요청내용', 
	RESPONSE_CONTENT TEXT  COMMENT '응답내용', 
	COUNSEL_CONTENT TEXT  COMMENT '상담내용', 
	COUNSEL_TYPE_CODE varchar(4) NOT NULL COMMENT '상담타입코드', 
	COUNSEL_PROGRESS_STATUS_CODE varchar(4) NOT NULL COMMENT '상담진행상태코드', 
	CREATE_USER_ID varchar(20) NOT NULL COMMENT '등록한사람아이디', 
	UPDATE_USER_ID varchar(20) NOT NULL COMMENT '수정한사람아이디', 
	DELETE_USER_ID varchar(20)  COMMENT '삭제한사람아이디', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14) NOT NULL COMMENT '수정일시', 
	DELETE_DATE_TIME varchar(14)  COMMENT '삭제일시'
);

ALTER TABLE TB_COUNSEL COMMENT ='상담';

CREATE TABLE TB_USER_CAREER (
	CAREER_NO int PRIMARY KEY COMMENT '일련번호', 
	USER_ID varchar(20) NOT NULL COMMENT '사용자 아이디', 
	DATE varchar(14) NOT NULL COMMENT '일시', 
	COMPANY_NAME varchar(20) NOT NULL COMMENT '회사명', 
	WORK_DEPARTMENT varchar(20) NOT NULL COMMENT '근무부서', 
	POSITION varchar(20) NOT NULL COMMENT '직위', 
	STATUS varchar(20) NOT NULL COMMENT '입퇴사구분', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14)  COMMENT '수정일시'
);

ALTER TABLE TB_USER_CAREER COMMENT ='경력';

CREATE TABLE TB_USER_EDUCATION (
	EDUCATION_NO int PRIMARY KEY COMMENT '일련번호', 
	USER_ID varchar(20) NOT NULL COMMENT '사용자 아이디', 
	DATE varchar(14) NOT NULL COMMENT '일시', 
	SCHOOL varchar(20) NOT NULL COMMENT '학교명', 
	MAJOR varchar(20) NOT NULL COMMENT '전공', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14)  COMMENT '수정일시'
);

ALTER TABLE TB_USER_EDUCATION COMMENT ='학력';

CREATE TABLE TB_USER_SELF_INTRODUCTION (
	USER_ID varchar(20) PRIMARY KEY COMMENT '사용자 아이디', 
	CONTENT_1 text  COMMENT '성장과정', 
	CONTENT_2 text  COMMENT '성격장단점', 
	CONTENT_3 text  COMMENT '기타경험', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14)  COMMENT '수정일시'
);

ALTER TABLE TB_USER_SELF_INTRODUCTION COMMENT ='자기소개서';

CREATE TABLE TB_SCHOOL (
	SCHOOL_CODE varchar(2) PRIMARY KEY COMMENT '학교코드', 
	SCHOOL_NAME varchar(10) NOT NULL COMMENT '학교이름', 
	CREATE_USER_ID varchar(20) NOT NULL COMMENT '등록한사람아이디', 
	UPDATE_USER_ID varchar(20) NOT NULL COMMENT '수정한사람아이디', 
	DELETE_USER_ID varchar(20)  COMMENT '삭제한사람아이디', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14) NOT NULL COMMENT '수정일시', 
	DELETE_DATE_TIME varchar(14)  COMMENT '삭제일시'
);

ALTER TABLE TB_SCHOOL COMMENT ='학교';

CREATE TABLE TB_DEPARTMENT (
	DEPARTMENT_CODE varchar(2) PRIMARY KEY COMMENT '학과코드', 
	DEPARTMENT_NAME varchar(10) NOT NULL COMMENT '학과이름', 
	CREATE_USER_ID varchar(20) NOT NULL COMMENT '등록한사람아이디', 
	UPDATE_USER_ID varchar(20) NOT NULL COMMENT '수정한사람아이디', 
	DELETE_USER_ID varchar(20)  COMMENT '삭제한사람아이디', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14) NOT NULL COMMENT '수정일시', 
	DELETE_DATE_TIME varchar(14)  COMMENT '삭제일시'
);

ALTER TABLE TB_DEPARTMENT COMMENT ='학과';

CREATE TABLE TB_USER_TYPE (
	USER_TYPE_CODE varchar(2) PRIMARY KEY COMMENT '사용자유형코드', 
	USER_TYPE_MEMO varchar(10) NOT NULL COMMENT '사용자유형설명', 
	CREATE_USER_ID varchar(20) NOT NULL COMMENT '등록한사람아이디', 
	UPDATE_USER_ID varchar(20) NOT NULL COMMENT '수정한사람아이디', 
	DELETE_USER_ID varchar(20)  COMMENT '삭제한사람아이디', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14) NOT NULL COMMENT '수정일시', 
	DELETE_DATE_TIME varchar(14)  COMMENT '삭제일시'
);

ALTER TABLE TB_USER_TYPE COMMENT ='사용자유형';

CREATE TABLE TB_REGISTER_STATUS (
	REGISTER_STATUS_CODE varchar(2) PRIMARY KEY COMMENT '학적상태코드', 
	REGISTER_STATUS_MEMO varchar(10) NOT NULL COMMENT '학적상태설명', 
	CREATE_USER_ID varchar(20) NOT NULL COMMENT '등록한사람아이디', 
	UPDATE_USER_ID varchar(20) NOT NULL COMMENT '수정한사람아이디', 
	DELETE_USER_ID varchar(20)  COMMENT '삭제한사람아이디', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14) NOT NULL COMMENT '수정일시', 
	DELETE_DATE_TIME varchar(14)  COMMENT '삭제일시'
);

ALTER TABLE TB_REGISTER_STATUS COMMENT ='학적상태';

CREATE TABLE TB_COUNSEL_TYPE (
	COUNSEL_TYPE_CODE varchar(2) PRIMARY KEY COMMENT '상담타입코드', 
	COUNSEL_TYPE_MEMO varchar(10) NOT NULL COMMENT '상담타입설명', 
	CREATE_USER_ID varchar(20) NOT NULL COMMENT '등록한사람아이디', 
	UPDATE_USER_ID varchar(20) NOT NULL COMMENT '수정한사람아이디', 
	DELETE_USER_ID varchar(20)  COMMENT '삭제한사람아이디', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14) NOT NULL COMMENT '수정일시', 
	DELETE_DATE_TIME varchar(14)  COMMENT '삭제일시'
);

ALTER TABLE TB_COUNSEL_TYPE COMMENT ='상담타입';

CREATE TABLE TB_COUNSEL_PROGRESS_STATUS (
	COUNSEL_PROGRESS_STATUS_CODE varchar(2) PRIMARY KEY COMMENT '상담진행상태코드', 
	COUNSEL_PROGRESS_STATUS_MEMO varchar(10) NOT NULL COMMENT '상담진행상태설명', 
	CREATE_USER_ID varchar(20) NOT NULL COMMENT '등록한사람아이디', 
	UPDATE_USER_ID varchar(20) NOT NULL COMMENT '수정한사람아이디', 
	DELETE_USER_ID varchar(20)  COMMENT '삭제한사람아이디', 
	CREATE_DATE_TIME varchar(14) NOT NULL COMMENT '등록일시', 
	UPDATE_DATE_TIME varchar(14) NOT NULL COMMENT '수정일시', 
	DELETE_DATE_TIME varchar(14)  COMMENT '삭제일시'
);

ALTER TABLE TB_COUNSEL_PROGRESS_STATUS COMMENT ='상담진행상태';
